services:

  postgres_db:
    container_name: postgres_db
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: userpassword
      POSTGRES_USER: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:6
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: api-franquicia
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: userpassword
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres_db
      - cache